version: '3'

services:
  postgres:
    image: postgres:12.3
    container_name: postgres_hotel_db
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotelBooking

  hotel-booking:
    image: hotel-booking
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_hotel_db:5432/hotelBooking
    depends_on:
      - postgres