version: '3'

services:
  postgres:
    image: postgres:12.3
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotelBooking

  hotel-booking:
    image: hotel-booking
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"